### ISSUE TITLE
Xdebug Profiler is always empty

### ISSUE THREAD

**Issue by tmishutin** [itsgoingd/clockwork#441]
HI.

I'm trying to setup clockwork for laravel (homestead setup laravel 7). I did all the setup. The problem is when I go to Profile tab in the request, it's trying to load first and then reports "Profile is not present for current request.". While in ajax response, there is data: {"xdebug":{"profile":"\/tmp\/cachegrind.out.3104"}}

And the file is actually there in /tmp/ folder. Can you help me out, where to dig?

**Comment by itsgoingd** [comment]
Hey, I can confirm this is an issue in Clockwork server-side and will be fixed in next patch release.

**Comment by itsgoingd** [comment]
Fixed in 5.0.2, thanks for reporting!

**Comment by tmishutin** [comment]
Can confirm, works now. Thank's for great work!

**Comment by helloiamlukas** [comment]
> EDIT: Mainly because it's within a .gz, but if I unzip it, and change the path in the json at the file itself, it works.

Make sure to add `xdebug.use_compression = false` in your `php.ini`

**Comment by marulitua** [comment]
Currently, on 5.1.6 and still have this issue.
This is my `xdebug_info()` output.
```
[1m__   __   _      _                 
[1m\ \ / /  | |    | |                
[1m \ V / __| | ___| |__  _   _  __ _ 
[1m  > < / _` |/ _ \ '_ \| | | |/ _` |
[1m / . \ (_| |  __/ |_) | |_| | (_| |
[1m/_/ \_\__,_|\___|_.__/ \__,_|\__, |
[1m                              __/ |
[1m                             |___/ 

[0mVersion => 3.1.5
Support Xdebug on Patreon, GitHub, or as a business: https://xdebug.org/support

             Enabled Features (through 'xdebug.mode' setting)             
Feature => Enabled/Disabled
Development Helpers => ✘ disabled
Coverage => ✘ disabled
GC Stats => ✘ disabled
Profiler => ✔ enabled
Step Debugger => ✘ disabled
Tracing => ✘ disabled

                            Optional Features                            
Compressed File Support => yes (gzip)
Clock Source => clock_gettime

                              Diagnostic Log                              
No messages

                                 Profiler                                 
Profiler is not active

                                   PHP                                   
                           Build Configuration                           
Version (Run Time) => 7.3.33
Version (Compile Time) => 7.3.33
Debug Build => no
Thread Safety => disabled
                                 Settings                                 
Configuration File (php.ini) Path => /usr/local/etc/php
Loaded Configuration File => (none)
Scan this dir for additional .ini files => /usr/local/etc/php/conf.d
Additional .ini files parsed => /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gd.ini,
/usr/local/etc/php/conf.d/docker-php-ext-imagick.ini,
/usr/local/etc/php/conf.d/docker-php-ext-intl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-redis.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sockets.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini,
/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini,
/usr/local/etc/php/conf.d/docker-php-ext-zip.ini,
/usr/local/etc/php/conf.d/manobo.ini


Directive => Local Value => Master Value
xdebug.mode => profile => profile
xdebug.start_with_request => trigger => trigger
xdebug.start_upon_error => default => default
xdebug.output_dir => /tmp/profiles => /tmp/profiles
xdebug.use_compression => no value => no value
xdebug.trigger_value => no value => no value
xdebug.file_link_format => no value => no value
xdebug.filename_format => no value => no value
xdebug.log => no value => no value
xdebug.log_level => 7 => 7
xdebug.var_display_max_children => 128 => 128
xdebug.var_display_max_data => 512 => 512
xdebug.var_display_max_depth => 3 => 3
xdebug.max_nesting_level => 256 => 256
xdebug.cli_color => 0 => 0
xdebug.force_display_errors => Off => Off
xdebug.force_error_reporting => 0 => 0
xdebug.halt_level => 0 => 0
xdebug.max_stack_frames => -1 => -1
xdebug.show_error_trace => Off => Off
xdebug.show_exception_trace => Off => Off
xdebug.show_local_vars => Off => Off
xdebug.dump.COOKIE => no value => no value
xdebug.dump.ENV => no value => no value
xdebug.dump.FILES => no value => no value
xdebug.dump.GET => no value => no value
xdebug.dump.POST => no value => no value
xdebug.dump.REQUEST => no value => no value
xdebug.dump.SERVER => no value => no value
xdebug.dump.SESSION => no value => no value
xdebug.dump_globals => On => On
xdebug.dump_once => On => On
xdebug.dump_undefined => Off => Off
xdebug.profiler_output_name => cachegrind.out.%p => cachegrind.out.%p
xdebug.profiler_append => Off => Off
xdebug.cloud_id => no value => no value
xdebug.client_host => localhost => localhost
xdebug.client_port => 9003 => 9003
xdebug.discover_client_host => Off => Off
xdebug.client_discovery_header => no value => no value
xdebug.idekey => no value => no value
xdebug.connect_timeout_ms => 200 => 200
xdebug.scream => Off => Off
xdebug.gc_stats_output_name => gcstats.%p => gcstats.%p
xdebug.trace_output_name => trace.%c => trace.%c
xdebug.trace_format => 0 => 0
xdebug.trace_options => 0 => 0
xdebug.collect_assignments => Off => Off
xdebug.collect_return => Off => Off
```
Looks like the problem is on the client side, because I can see this response
```
{"xdebug":{"profile":"\/tmp\/profiles\/cachegrind.out.24","profileData":"version: 1\ncreator: xdebug 3.1.5 (PHP 7.3.33)\ncmd: \/app\/server.php\npart: 1\npositions: line\n\nevents: Time_(10ns) Memory_(bytes)\n\nfl=(1) 
```

**Comment by itsgoingd** [comment]
@marulitua Hey, you can try some suggestions from this issue - https://github.com/underground-works/clockwork-app/issues/109. If it doesn't help, please send me a sample profile to info@underground.works.

**Comment by marulitua** [comment]
Thanks! It works now!
In my case, I have to add this config
```
xdebug.profiler_output_name=cachegrind.out.%R.%u
xdebug.use_compression=false
```

**Comment by mikadev** [comment]
not working at all on windows i see the file but clockwork no
